[platformio]
default_envs = a2dp_sink_control

[env:a2dp_sink_control]
platform = espressif32@7.1.3
platform_packages = platformio/framework-espidf@4.60100.0
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200
